services:
  org_service:
    container_name: org_service
    build:
      context: ../..
      dockerfile: services/org/Dockerfile
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    ports:
      - "3003:3000"
    depends_on:
      - database
    networks:
      - database-network
      - backend-network

networks:
  database-network:

  backend-network:
