services:
  submission_service:
    container_name: submission_service
    build:
      context: ../..
      dockerfile: services/submission/Dockerfile
    env_file:
      - ../../.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
    ports:
      - "3007:3000"
    depends_on:
      - database
    networks:
      - database-network
      - backend-network

networks:
  database-network:

  backend-network:
