services:
  backend:
    container_name: backend

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      - PORT=3000
      - DB_PORT=5432
      - DB_HOST=database
      - DB_DATABASE=${POSTGRES_DB}
      - DB_NAME=${POSTGRES_USER}

    expose:
      - 3000

    networks:
      - database-network
      - backend-network

    depends_on:
      database:
        condition: service_healthy

    secrets:
      - db_password
    

networks:
  database-network:

  backend-network:
