services:
  nginx:
    container_name: nginx

    build:
      context: .
      dockerfile: Dockerfile

    command: ["nginx", "-g", "daemon off;"]

    volumes:
      - ./conf.d:/etc/nginx/conf.d

    networks:
      - backend-network
      - frontend-network

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - frontend

networks:

  backend-network:

  
  frontend-network:
