include:
  - database/docker-compose.yml
  - frontend/docker-compose.yml
  - nginx/docker-compose.yml
  - services/user/docker-compose.yml


volumes:
  postgres_data:

networks:

  database-network:

  backend-network:

  frontend-network: